set(_CATKIN_CURRENT_PACKAGE "plane_calibration")
set(plane_calibration_VERSION "0.2.0")
set(plane_calibration_MAINTAINER "Alexander Reimann <Rei.man.nalex8.8+ROS_PC@gmail.com>")
set(plane_calibration_PACKAGE_FORMAT "1")
set(plane_calibration_BUILD_DEPENDS "ecl_build" "ecl_geometry" "cmake_modules" "roscpp" "nodelet" "dynamic_reconfigure" "sensor_msgs" "geometry_msgs" "tf2" "tf2_msgs" "image_geometry" "depth_image_proc" "eigen_conversions" "tf2_ros")
set(plane_calibration_BUILD_EXPORT_DEPENDS "ecl_build" "ecl_geometry" "roscpp" "nodelet" "dynamic_reconfigure" "sensor_msgs" "geometry_msgs" "tf2" "tf2_msgs" "image_geometry" "depth_image_proc" "eigen_conversions" "tf2_ros")
set(plane_calibration_BUILDTOOL_DEPENDS "catkin")
set(plane_calibration_BUILDTOOL_EXPORT_DEPENDS )
set(plane_calibration_EXEC_DEPENDS "ecl_build" "ecl_geometry" "roscpp" "nodelet" "dynamic_reconfigure" "sensor_msgs" "geometry_msgs" "tf2" "tf2_msgs" "image_geometry" "depth_image_proc" "eigen_conversions" "tf2_ros")
set(plane_calibration_RUN_DEPENDS "ecl_build" "ecl_geometry" "roscpp" "nodelet" "dynamic_reconfigure" "sensor_msgs" "geometry_msgs" "tf2" "tf2_msgs" "image_geometry" "depth_image_proc" "eigen_conversions" "tf2_ros")
set(plane_calibration_TEST_DEPENDS )
set(plane_calibration_DOC_DEPENDS )
set(plane_calibration_URL_WEBSITE "")
set(plane_calibration_URL_BUGTRACKER "")
set(plane_calibration_URL_REPOSITORY "")
set(plane_calibration_DEPRECATED "")